############## Differential Drive ##############
cyclops_base_controller:
  # BASETYPE
  # 0 => joint_control 
  # 1 => diff_drive **developing
  # 2 => skidsteer_drive **developing
  # 3 => omni3_drive **developing
  # 4 => omni4_drive **developing
  # 5 => mecanum_drive **developing
  # 6 => ackermann_drive **developing
  base_type: 1
  
  cmd_vel_timeout: 600 # millisec for timeout 
  enable_odom_tf: True
  use_imu: True

  max_linear_vel: 0.3 # m/s x axis
  max_angular_vel: 90.0 # deg/s 
  # max_linear_accel: 1.0 # m/s^2 UNUSED
  # max_angular_accel: 180.0 # deg/s^2 UNUSED

  left_wheel: #[MotorEnc1]
    motor_rpm: 100 # MOTOR_MAX_RPM [rpm]
    encoder_ppr: 32000 # ENCODER_COUNT_PER_REV [ppr]
    pid: [3.0, 0.1, 0.0]  # Kp, TauI, TauD
  right_wheel: #[MotorEnc2]
    motor_rpm: 100 # MOTOR_MAX_RPM [rpm]
    encoder_ppr: 32000 # ENCODER_COUNT_PER_REV [ppr]
    pid: [3.0, 0.1, 0.0]  # Kp, TauI, TauD

  wheel_radius: 0.073 # WHEEL_RADIUS [m]
  wheel_separation: 0.45 # WHEEL_SEPARATION [m] 
  
 

  # Diagonal of the covariance matrix for odometry pose publishing 
  pose_covariance_diagonal: [-1.0, 0.0, 0.0] #cov x, y, yaw
  twist_covariance_diagonal: [-1.0, 0.0] #cov vx, vyaw
###################################################